version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: utilix-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./apps/api:/app/api
    depends_on:
      - redis
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: utilix-web
    ports:
      - "4200:80"
    environment:
      NODE_ENV: production
      API_URL: https://utilix-api.querc.app
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
    depends_on:
      - api
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: utilix-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
